apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-host
  name: nginx-host
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-host
    spec:
      containers:
      - image: divoivo/nginx-host:%IMAGE-PLACEHOLDER%
        name: nginx-host
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
